// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0nMqhkgLSiWD66XanIkBpuJwakPBP3w',
    appId: '1:908160509388:web:31c86fe02a6d554663e969',
    messagingSenderId: '908160509388',
    projectId: 'fasum-app-b0173',
    authDomain: 'fasum-app-b0173.firebaseapp.com',
    databaseURL: 'https://fasum-app-b0173-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-b0173.appspot.com',
    measurementId: 'G-6S8Y17YNBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBHeqY3A2KXbe5mu_lKICi5R1AjMqVpY',
    appId: '1:908160509388:android:2f332c9c00861bb963e969',
    messagingSenderId: '908160509388',
    projectId: 'fasum-app-b0173',
    databaseURL: 'https://fasum-app-b0173-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-b0173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTV2r0yIThyebRY4_9-howtG7RrIgr_4g',
    appId: '1:908160509388:ios:a1a66fde1abdb60563e969',
    messagingSenderId: '908160509388',
    projectId: 'fasum-app-b0173',
    databaseURL: 'https://fasum-app-b0173-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-b0173.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTV2r0yIThyebRY4_9-howtG7RrIgr_4g',
    appId: '1:908160509388:ios:0ba2d9a5b3446e6463e969',
    messagingSenderId: '908160509388',
    projectId: 'fasum-app-b0173',
    databaseURL: 'https://fasum-app-b0173-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-b0173.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
